apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cbcontainers-access-token
  namespace: cbcontainers-dataplane
spec:
  encryptedData:
    accessToken: AgB4cxmo4NBM+YGUhhfLKgHfwaduFNS/qATv3ZoKB7vbhPWy5tDh5UkA/dHeCAsmzzq39fjiH2Bbtf08Qo086n6RV8V1LfhiY1at2tKD3MT1GiwikcZGwWJ1GmzWUFa0TtA8k7Fn1RrWNRnfvsyrcMavvCwzhvtN/iGJqIBbotwqnPlcIar5bQ5ujHIsO9BMSp4ZQX1rS/VSw8NNg1TJzt7DJRv04DP8nUHhfZLcQaE9DwdTOo9xN0mhfPzgJKq3o/yemqZt20dqeoA54By3PytKgrgbIW4LXnZqdngNvOvy9BKezIBytsCPCSCaX9Q40Y671r+/lNhyRCdvfftf6psefHMeevLdU5bSfiFjPS1sssG3LQWw341b/0pZvI5hg1egvqtzIMpU7a9zkVM2qS+sFP2GwOhfoiEtol3MI4XujftYl40TahkgRg8DjhQowqzrsIzVoXVprMKP2q2qHBzY4ikCgBHP6HhiW1OH5Lk5RNl2gzVjhEQJkF284GYiTuzBaSe/38lLFkNSiRfBsOEg6iWQ7yjn+SPG4iojucrVfdg6vgLKKNqgLPrz0Z/xMzUNd8iOjoyReziOUzxblD5iDN6vzRybTGHXjPQ25V4U3gBqabl52C+i6QQeJ8NdRDW6UMXkUwf3eRs5pVl69wwY7fvd0wh2RFnrUMsLIGSmQT1k2JZZsN/9MTp/9hBYUMt4xjEcOGHJuHPnO3ua8gX5ecFrOAFFp0cWB1dwGCgUko6nyg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cbcontainers-access-token
      namespace: cbcontainers-dataplane

