apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/carbon-black
  - cbcontainers-access-token_sealedsecret.yaml
patchesStrategicMerge:
  - patch-cbcontainers-agent_helmrelease.yaml
