apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cbcontainers-operator
  namespace: flux-system
spec:
  releaseName: cbcontainers-operator
  targetNamespace: cbcontainers-dataplane
  chart:
    spec:
      chart: charts/cbcontainers-operator/cbcontainers-operator-chart
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: octarine-operator
        namespace: flux-system
  interval: 1h0m0s
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
