apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: octarine-operator
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: master
  timeout: 60s
  url: https://github.com/octarinesec/octarine-operator.git